### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wf-soft** [R2D221/WebView2.DOM#1]
@R2D221  Hi! R2D221.

`System.NotImplementedException:“Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Experimental.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning”
`

`InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Experimental'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{31F05BAC-FFBB-4071-9355-7E57E3F18E50}' failed due to the following error: 不支持此接口 (0x80004002 (E_NOINTERFACE)).
`

**Comment by wf-soft** [comment]
It seems that the webview2 runtime version is low. I must install the Microsoft edge dev version and uninstall the webview2 runtime to work properly

**Comment by R2D221** [comment]
Sure, I'll make sure to update to the latest WebView2 version

**Comment by wf-soft** [comment]
@R2D221 I want to know what better way I can do something in a series of multiple completion event jumps；

**Comment by R2D221** [comment]
Just for the record, I now target the latest WebView2 stable in v0.0.4

https://www.nuget.org/packages/WebView2.DOM/0.0.4
