### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by kevinp1335** [R2D221/WebView2.DOM#14]
I've been using this for a while and it quit working yesterday. I tried updating to the latest version of this and Microsoft.Web.WebView2. Changed my target framework to NET 6 as well. Working with WinForms.

In my DOMContentLoaded method I have this line where the program now crashes:

foreach (var curElement in window.document.getElementsByTagName("div"))

It's giving me the error:

WebView2.DOM.TypeError: 'Cannot read properties of undefined (reading 'constructor')'

It's been working for quite a while, but quit yesterday. Not sure what changed.

**Comment by R2D221** [comment]
Let me take a look at it.

**Comment by R2D221** [comment]
It's fixed. You can update to version 0.7.2.

**Comment by kevinp1335** [comment]
0.7.3 is what shows up in Nuget. Confirmed it is now working. Thank you.
