### ISSUE TITLE
How to use this method for finding an element using XPath?

### ISSUE THREAD

**Issue by fatkulamri** [R2D221/WebView2.DOM#6]
Please help,

How to use this method for finding an element using XPath?

**Comment by R2D221** [comment]
Sorry to take this long to respond.

I thought this was already implemented as part of the base API, but I see I didn't include the document.evaluate method.

I'll let you know when it's implemented.

**Comment by R2D221** [comment]
WebView2.DOM v0.2.2 now includes the XPath APIs and now can be used with this library. The same you would do it with vanilla JS can be used here, such as this: https://developer.mozilla.org/en-US/docs/Web/XPath/Introduction_to_using_XPath_in_JavaScript
