### ISSUE TITLE
Can't install nuget WebView2.DOM 0.1.3 on Windows 10

### ISSUE THREAD

**Issue by zydjohnHotmail** [R2D221/WebView2.DOM#7]
Hello:
I want to try your repo. I have done the following:
1. Create one C# console app with target .net 5.0 on Windows 10 (Version 20H2)
(OS Build 19042.870)
2. Install webview2:
Install-Package Microsoft.Web.WebView2 -Version 1.0.824-prerelease
3. Install WebView2.DOM:
Install-Package WebView2.DOM -Version 0.1.3

But I got the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package WebView2.DOM 0.1.3 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package WebView2.DOM 0.1.3 supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)	WebView2DOMTest	C:\WebView2DOMTest\WebView2DOMTest.csproj
I think there was some configuration not correct in the nuget package, please check and change it.
Thanks,

**Comment by R2D221** [comment]
Hi. This project requires either a WinForms or a WPF project to be installed via NuGet. Console app doesn't work because by default it's cross platform, while the WinForms and WPF projects are Windows only. Hence the “net5.0-windows7.0” version on my package.
