### ISSUE TITLE
Backport it to dotnet core 3.1

### ISSUE THREAD

**Issue by GunArm** [R2D221/WebView2.DOM#9]
We are currently deploying with dotnet core 3.1 instead of net 5, because 3.1 is an LTS and will stay in support until Dec 2022 whereas net5 will leave support "around February 2022" https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Do you think there are any BCL/language changes between net5 and 3.1 that would make it difficult to publish a nuget package for 3.1?  I would (naively) expect it to be a lot less work than Framework 4.6.2 support.

**Comment by R2D221** [comment]
Sorry for checking this until now. I've been busy.

But yeah, let me check if I can set it to compile for .NET Core 3.1. I'll let you know how it goes

**Comment by R2D221** [comment]
While not as trivial as I initially thought (I'm using C# 9 records for IDL dictionaries), I can confirm I will make a .NET Core 3.1 version available in the next few days.

**Comment by R2D221** [comment]
I've uploaded version 0.2.0 which should be compatible with .NET Core 3.1. Please let me know if you run into any problems.

**Comment by GunArm** [comment]
By the way, thank you for this!
